services:
  mitmproxy:
    container_name: mitmproxy
    platform: linux/amd64
    build:
      dockerfile: docker/Dockerfile
      context: ..
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017